### ISSUE TITLE
Is this project alive and open to collaboration?

### ISSUE THREAD

**Issue by thclark** [flamingo-run/gcp-pilot#38]
So I've submitted an issue that never got touched, and assumed this project was dead... but have noticed a couple of version bumps recently.

Questions:
- is someone maintaining it?

- if so, who?

- where are the contributing guidelines and what's the release flow?

- the only issues on this board are raised by me, so where's the issues board you're using? And is there a release roadmap/plan?

- do you need help?

- have you considered getting sponsorship from Google (because really, this is a very good project compared to google's in-house "sdks" which are a nightmare to work with)?

(and because I noticed that you've deprecated support for python <3.10)

- are you aware google use ridiculously out of date python versions (e.g. dataflow only supports up to 3.9), so to get any kind of acceptance you'll need to keep some backward compatibility?

**Comment by joaodaher** [comment]
Hey @thclark ! Sorry for the absence of response, this notification might have got lost.

> is someone maintaining it?
I maintain this repo as a side project, it is [heavily used](https://github.com/flamingo-run/gcp-pilot/releases) in some companies I've been working.
Some of my colleagues also help from time to time.

> where are the contributing guidelines and what's the release flow?
You can just fork and make a PR. The CI/CD should take care of some minor guidelines, but the testing is still quite manual since there's no integration test with Google APIs.

> the only issues on this board are raised by me, so where's the issues board you're using?
The issues that my team encounter are immediately resolved (as you may see by the constant releases).

>  And is there a release roadmap/plan?
We try to make releases as soon as possible. We test a lot and release.
It might not the most stable library, but it allows us to "break fast, change fast".

> do you need help?
Sure, everything we might think you can add is very welcome. 🙏 

> have you considered getting sponsorship from Google 
I did not, really. Google has been gradually adding better libraries (one for each service).
This project mainly helps with those very beta-stage APIs that have no dedicated library.

> are you aware google use ridiculously out of date python versions
Yeah, I like to keep things up-to-date to use the cool features, and this repo usually follows up these projects, since I didn't have many other users, really.
And I agree repo could have more retro-compatibility, we're just missing more tests and release cycles.
